name: video_player_macos
description: MacOS implementation of the video_player plugin.
version: 1.0.4
homepage: https://github.com/ollydixon/flutter_macos_video_player

flutter:
  plugin:
    implements: video_player
    platforms:
      macos:
        pluginClass: FLTVideoPlayerPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^5.1.1

dev_dependencies:
  pedantic: ^1.10.0
