name: video_player_macos
description: MacOS implementation of the video_player plugin.
version: 2.0.0
homepage: https://github.com/ollydixon/flutter_macos_video_player

flutter:
  plugin:
    implements: video_player
    platforms:
      macos:
        pluginClass: FLTVideoPlayerPlugin
        dartPluginClass: VideoPlayerMacOs

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.0.1

dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^8.0.0
